<a href="https://colab.research.google.com/github/long14dhth06-spec/TH_DeepLearning/blob/main/TH_DEEP_LEARNING_NUMPY_PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#CÀI ĐẶT NUMPY
!pip install numpy

In [6]:
import numpy as np
#TẠO NUMPY ARRAY
#3.1 TẠO ARRAY 1 CHIỀU
#cách 1
#tạo list
my_list = [1, 9, 15, 39]
print ('Python list:',my_list)
#chuyển list --> Numpy array
my_numpy_array = np.array(my_list)
print ('Numpy array:',my_numpy_array)
#Cách 2
a = np.array([1, 9, 15, 39])
print(a)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
[ 1  9 15 39]


In [7]:
#3.2 ARRAY 2 CHIỀU
c = np.array([(1, 2, 3),
              (4, 5, 6)
              ])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [8]:
#3.3 ARRAY 3 CHIỀU
d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]],
])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [9]:
#3.4 TẠO ARRAY VỚI GIÁ TRỊ BAN ĐẦU LÀ 0 HOẶC 1
e = np.zeros((2,2))
f = np.ones((3,3))
print('Zero matrix:\n',e)
print('One matrix:\n',f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
#1. Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20].Viết chương trình kiểm tra tất cả các phần tử trong mảng khác 0 (tìm hiểu hàm all của numpy)
a = np.random.randint(20, size =(3,3))
print(a)
np.all(a, axis = None, out = None, keepdims = False)


[[ 1 13  4]
 [19 15  5]
 [ 7 14 11]]


np.True_

In [19]:
#2. Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết chương trình kiểm tra tồn tại một phần tử trong mảng khác 0 (tìm hiểu hàm any của numpy)
a = np.random.randint(20, size =(3,3))
print(a)
np.any(a)

[[15  1 15]
 [16 12  1]
 [ 0  6 19]]


np.True_

In [46]:
#3. Sinh viên tìm hiểu và viết chương trình sử dụng các hàm sau numpy.greater, numpy.greater_equal, numpy.less, và numpy.less_equal để so sánh 2 mảng 1 chiều, 2 chiều.
a = np.random.randint(20, size =(3,3))
b = np.random.randint(20, size =(3,3))
print(a)
print(b)
np.greater(a, b)
np.greater_equal(a, b)
np.less(a, b)
np.less_equal(a, b)

c = np.array([(1,2,3),
             (4,5,6)])
d = np.array([(1,2,3),
             (7,8,9)])
print(c)
print(d)
np.greater_equal(c, d)
np.less_equal(c, d)
np.greater(c, d)
np.less(c, d)

[[ 9 19 19]
 [ 0  8 11]
 [16  6 14]]
[[ 7 13 10]
 [16 12 11]
 [10  7 11]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [7 8 9]]


array([[False, False, False],
       [ True,  True,  True]])

In [52]:
#4. Viết chương trình tạo mảng gồm 10 số 1, 10 số 0 và 10 số 5
a = np.zeros(10)
b = np.ones(10)
c = np.full(10,5)
kq = np.concatenate((a,b,c))
print(kq)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [56]:
#5. Viết chương trình tạo mảng số nguyên chẳn từ [30, 70]
a = np.arange(30,71,2)
print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [60]:
#7. Viết chương trình tạo mảng 10 phần tử trong khoảng [15, 55]. In các giá trị ngoài trừ phần tử đầu và cuối
arr = np.random.randint(15, 56, 10)
print(arr[1:-1])

[51 15 30 25 36 45 52 37]


In [59]:
#6. Viết chương trình tạo ma trận đơn vị 3 x 3 (đường chéo chính bằng 1, các phần tử còn lại 0) (Tìm hiểu hàm identity của numpy)
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [70]:
#8. Viết chương trình tạo mảng 20 phần tử trong khoảng [0, 20] và đổi dấu những số nằm trong khoảng [9, 15]
a = np.linspace(0,20,20)
print(a)
mask = (a>=9) & (a<=15)
a[mask] = -a[mask]
print(a)

[ 0.          1.05263158  2.10526316  3.15789474  4.21052632  5.26315789
  6.31578947  7.36842105  8.42105263  9.47368421 10.52631579 11.57894737
 12.63157895 13.68421053 14.73684211 15.78947368 16.84210526 17.89473684
 18.94736842 20.        ]
[  0.           1.05263158   2.10526316   3.15789474   4.21052632
   5.26315789   6.31578947   7.36842105   8.42105263  -9.47368421
 -10.52631579 -11.57894737 -12.63157895 -13.68421053 -14.73684211
  15.78947368  16.84210526  17.89473684  18.94736842  20.        ]


In [77]:
#9. Viết chương trình tạo ma trận 3 x 4 và mỗi phần tử có giá trị [10, 21]
a = np.random.randint(10,22, size=(3,4))
print(a)

[[21 16 12 10]
 [12 21 10 12]
 [20 17 16 14]]


In [78]:
#10. Viết chương trình tạo ma trận 10 x 10, các phần tử ở biên có giá trị 1, các phần tử bên trong có giá trị 0
a = np.zeros((10, 10), dtype=int)

# Gán các biên = 1
a[0, :] = 1      # hàng trên
a[-1, :] = 1     # hàng dưới
a[:, 0] = 1      # cột trái
a[:, -1] = 1     # cột phải

print(a)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [80]:
#11. Viết chương trình tạo ma trận 5 x 5, các phần tử ở đường chéo chính là 1, 2, 3, 4, 5. (tìm hiểu hàm diag của numpy)
a = np.array([1,2,3,4,5])
b = np.diag(a)
print(b)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [83]:
#12. Viết chương trình tạo mảng 3 x 3 x 3 và tính tổng theo mỗi dòng, mỗi cột. (tìm hiểu hàm sum của numpy)
a = np.arange(1,28).reshape(3,3,3)
print(a)
Sum_col = np.sum(a, axis=0)
print(Sum_col)
Sum_row = np.sum(a, axis=1)
print(Sum_row)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[30 33 36]
 [39 42 45]
 [48 51 54]]
[[12 15 18]
 [39 42 45]
 [66 69 72]]


In [ ]:
13. Tạo 2 vector ngẫu nhiên 10 phần tử. Thực hiện inner product (np.dot)
14. Tạo ma trận A= 4 x 3 và vector y gồm 3 phần tử ngẫu nhiên. Thêm vector y vào từng dòng của
ma trận A
15. Viết chương trình Pandas để cộng, trừ, nhân, chia 2 Series : [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]
16. Viết chương trình Pandas chuyển đổi cột đầu tiên thành Series (Tìm hiểu thuộc tính ix của
pandas)